apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8stest
  labels:
    app: {{.Values.deployment.labels}}
    logenabled: {{.Values.deployment.logenabled}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.deployment.selector}}
      logenabled: {{.Values.deployment.logenabled}}
  template:
    metadata:
      labels:
        app: k8stest
        logenabled: {{.Values.deployment.logenabled}}
    spec:
      containers:
      - name: k8stest
        image: {{.Values.image.repository}}:{{.Values.imagetag}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secretvolume
          mountPath: root/.aws 
          readOnly: false
      volumes:
      - name: secretvolume
        secret:
          secretName: aws-secret
       
      #restartPolicy: Always





      
