apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.9.0
  nodeSets:
  - name: master-data-ingest
    count: 1
    # http:
    #   service:
    #     spec:
    #       type: ClusterIP # default is ClusterIP
    #       tls:
    #         selfSignedCertificate:
    #           disabled: true  
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              memory: 4Gi
              cpu: 0.5
            limits:
              memory: 4Gi
              cpu: 2 
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /mnt/data   
        volumes:
        - name: elasticsearch-data
          hostpath:
            path: /mnt/data    
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false 
  # - name: ingest
  #   count: 1
  #   podTemplate:
  #     spec:
  #       volumes:
  #         - .name: elasticsearch-data
  #           emptyDir: {}
  #       containers:
  #       - name: elasticsearch
  #         env:
  #         - name: ES_JAVA_OPTS
  #           value: -Xms2g -Xmx2g
  #         resources:
  #           requests:
  #             memory: 2Gi
  #             cpu: 0.5
  #           limits:
  #             memory: 2Gi
  #             cpu: 2      
  #   config:
  #     node.master: false
  #     node.data: false
  #     node.ingest: true
  #     node.store.allow_mmap: false 
  # - name: cordinator
  #   count: 1
  #   podTemplate:
  #     spec:
  #       volumes:
  #         - name: elasticsearch-data
  #           emptyDir: {}
  #       containers:
  #       - name: elasticsearch
  #         env:
  #         - name: ES_JAVA_OPTS
  #           value: -Xms2g -Xmx2g
  #         resources:
  #           requests:
  #             memory: 2Gi
  #             cpu: 0.5
  #           limits:
  #             memory: 2Gi
  #             cpu: 2      
  #   config:
  #     node.master: false
  #     node.data: false
  #     node.ingest: false
  #     node.cordinator: true
  #     node.store.allow_mmap: false 
      

    # volumeClaimTemplates:
    # - metadata:
    #     name: elasticsearch-data
    #   spec:
    #     accessModes:
    #     - ReadWriteOnce
    #     resources:
    #       requests:
    #         storage: 1Gi
    #     storageClassName: standard 
---
 

         